# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/AudioFilters/AudioFilters.srcs/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xci
# IP: The module: 'block_design_microblaze_riscv_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Vivado/AudioFilters/AudioFilters.srcs/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xci
# IP: The module: 'block_design_microblaze_riscv_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_microblaze_riscv_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
