# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Vivado/AudioFilters/AudioFilters.runs/synth_1/block_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 3
set_param bd.open.in_stealth_mode 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/AudioFilters/AudioFilters.cache/wt [current_project]
set_property parent.project_path D:/Vivado/AudioFilters/AudioFilters.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.2 [current_project]
set_property ip_repo_paths {
  d:/Vivado/AudioFilters/vivado-library
  d:/Vivado/AudioFilters/AudioFilters.ipdefs/repo/local/ip/d_axi_i2s_audio_v2_0
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/Vivado/AudioFilters/AudioFilters.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib D:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/hdl/block_design_wrapper.v
add_files D:/Vivado/AudioFilters/AudioFilters.srcs/sources_1/bd/block_design/block_design.bd
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_0/block_design_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_0/block_design_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_0/block_design_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_dlmb_v10_0/block_design_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_ilmb_v10_0/block_design_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_dlmb_bram_if_cntlr_0/block_design_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_ilmb_bram_if_cntlr_0/block_design_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_lmb_bram_0/block_design_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_22f9_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_22f9_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_22f9_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_22f9_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_22f9_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_22f9_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_22f9_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_22f9_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_22f9_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_22f9_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_22f9_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_22f9_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_19/bd_22f9_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_22f9_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_22f9_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_22f9_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_22f9_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_22f9_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_22f9_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_22f9_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_22f9_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_22f9_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_22f9_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_22f9_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_22f9_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_22f9_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_22f9_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_22f9_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_22f9_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_22f9_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_22f9_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_22f9_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_22f9_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_22f9_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_53/bd_22f9_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_54/bd_22f9_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_55/bd_22f9_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_56/bd_22f9_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_57/bd_22f9_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_58/bd_22f9_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_60/bd_22f9_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_61/bd_22f9_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_62/bd_22f9_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_63/bd_22f9_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_64/bd_22f9_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_65/bd_22f9_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_67/bd_22f9_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_68/bd_22f9_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_69/bd_22f9_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_70/bd_22f9_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_71/bd_22f9_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_72/bd_22f9_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_74/bd_22f9_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_75/bd_22f9_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_76/bd_22f9_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_77/bd_22f9_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_78/bd_22f9_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_79/bd_22f9_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_81/bd_22f9_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_82/bd_22f9_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_83/bd_22f9_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_84/bd_22f9_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_85/bd_22f9_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_86/bd_22f9_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_88/bd_22f9_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_89/bd_22f9_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_90/bd_22f9_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_91/bd_22f9_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_92/bd_22f9_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_93/bd_22f9_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_95/bd_22f9_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_96/bd_22f9_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_97/bd_22f9_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_98/bd_22f9_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_99/bd_22f9_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_100/bd_22f9_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_102/bd_22f9_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_103/bd_22f9_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_104/bd_22f9_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_105/bd_22f9_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_106/bd_22f9_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_107/bd_22f9_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_mdm_1_0/block_design_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_mdm_1_0/block_design_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_rst_clk_wiz_1_100M_0/block_design_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_rst_clk_wiz_1_100M_0/block_design_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/constraints/block_design_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0/user_design/constraints/block_design_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_pmod_bridge_0_0/PmodOLED_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/block_design_PmodOLED_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_quad_spi_0_0/PmodOLED_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_PmodOLED_0_0/src/PmodOLED_axi_gpio_0_0/PmodOLED_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_dma_0_0/block_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_dma_0_0/block_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_dma_0_0/block_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_iic_0_0/block_design_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_iic_0_0/block_design_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/src/d_axi_i2s_audio.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/block_design_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/AudioFilters/AudioFilters.srcs/constrs_1/new/Nexys_Video.xdc
set_property used_in_implementation false [get_files D:/Vivado/AudioFilters/AudioFilters.srcs/constrs_1/new/Nexys_Video.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/Vivado/AudioFilters/AudioFilters.srcs/utils_1/imports/synth_1/block_design_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top block_design_wrapper -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef block_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file block_design_wrapper_utilization_synth.rpt -pb block_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
