# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys_Video.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_riscv_0_0/block_design_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_riscv_0_0 || ORIG_REF_NAME==block_design_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_dlmb_v10_0/block_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_dlmb_v10_0 || ORIG_REF_NAME==block_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ilmb_v10_0/block_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_ilmb_v10_0 || ORIG_REF_NAME==block_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_dlmb_bram_if_cntlr_0/block_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==block_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ilmb_bram_if_cntlr_0/block_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==block_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_lmb_bram_0/block_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_lmb_bram_0 || ORIG_REF_NAME==block_design_lmb_bram_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==block_design_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_riscv_0_axi_intc_0/block_design_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==block_design_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_mdm_1_0/block_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_mdm_1_0 || ORIG_REF_NAME==block_design_mdm_1_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_rst_clk_wiz_1_100M_0/block_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==block_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_mig_7series_0_0 || ORIG_REF_NAME==block_design_mig_7series_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_PmodOLED_0_0/block_design_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_PmodOLED_0_0 || ORIG_REF_NAME==block_design_PmodOLED_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_dma_0_0/block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_dma_0_0 || ORIG_REF_NAME==block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_iic_0_0/block_design_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_iic_0_0 || ORIG_REF_NAME==block_design_axi_iic_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_gpio_0_0 || ORIG_REF_NAME==block_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_d_axi_i2s_audio_0_0/block_design_d_axi_i2s_audio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_d_axi_i2s_audio_0_0 || ORIG_REF_NAME==block_design_d_axi_i2s_audio_0_0} -quiet] -quiet

# XDC: d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/block_design_ooc.xdc
