# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "block_design_microblaze_riscv_0_axi_periph_0_synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/AudioFilters/AudioFilters.cache/wt [current_project]
set_property parent.project_path D:/Vivado/AudioFilters/AudioFilters.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.2 [current_project]
set_property ip_repo_paths {
  d:/Vivado/AudioFilters/vivado-library
  d:/Vivado/AudioFilters/AudioFilters.ipdefs/repo/local/ip/d_axi_i2s_audio_v2_0
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/Vivado/AudioFilters/AudioFilters.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet D:/Vivado/AudioFilters/AudioFilters.srcs/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0.xci
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_22f9_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_22f9_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_22f9_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_22f9_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_22f9_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_22f9_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_22f9_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_22f9_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_22f9_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_22f9_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_22f9_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_22f9_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_19/bd_22f9_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_22f9_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_22f9_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_22f9_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_22f9_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_22f9_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_22f9_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_22f9_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_22f9_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_22f9_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_22f9_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_22f9_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_22f9_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_22f9_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_22f9_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_22f9_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_22f9_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_22f9_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_22f9_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_22f9_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_22f9_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_22f9_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_53/bd_22f9_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_54/bd_22f9_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_55/bd_22f9_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_56/bd_22f9_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_57/bd_22f9_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_58/bd_22f9_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_60/bd_22f9_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_61/bd_22f9_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_62/bd_22f9_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_63/bd_22f9_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_64/bd_22f9_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_65/bd_22f9_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_67/bd_22f9_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_68/bd_22f9_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_69/bd_22f9_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_70/bd_22f9_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_71/bd_22f9_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_72/bd_22f9_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_74/bd_22f9_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_75/bd_22f9_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_76/bd_22f9_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_77/bd_22f9_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_78/bd_22f9_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_79/bd_22f9_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_81/bd_22f9_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_82/bd_22f9_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_83/bd_22f9_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_84/bd_22f9_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_85/bd_22f9_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_86/bd_22f9_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_88/bd_22f9_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_89/bd_22f9_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_90/bd_22f9_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_91/bd_22f9_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_92/bd_22f9_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_93/bd_22f9_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_95/bd_22f9_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_96/bd_22f9_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_97/bd_22f9_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_98/bd_22f9_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_99/bd_22f9_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_100/bd_22f9_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_102/bd_22f9_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_103/bd_22f9_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_104/bd_22f9_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_105/bd_22f9_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_106/bd_22f9_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_107/bd_22f9_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_109/bd_22f9_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_110/bd_22f9_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_111/bd_22f9_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_112/bd_22f9_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_113/bd_22f9_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_114/bd_22f9_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/smartconnect.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1 -new_name block_design_microblaze_riscv_0_axi_periph_0 -ip [get_ips block_design_microblaze_riscv_0_axi_periph_0]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top block_design_microblaze_riscv_0_axi_periph_0 -part xc7a200tsbg484-1 -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix block_design_microblaze_riscv_0_axi_periph_0_ block_design_microblaze_riscv_0_axi_periph_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ block_design_microblaze_riscv_0_axi_periph_0_stub.v
 lappend ipCachedFiles block_design_microblaze_riscv_0_axi_periph_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl
 lappend ipCachedFiles block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.v
 lappend ipCachedFiles block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.vhdl
 lappend ipCachedFiles block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp block_design_microblaze_riscv_0_axi_periph_0.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips block_design_microblaze_riscv_0_axi_periph_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all block_design_microblaze_riscv_0_axi_periph_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef block_design_microblaze_riscv_0_axi_periph_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file block_design_microblaze_riscv_0_axi_periph_0_utilization_synth.rpt -pb block_design_microblaze_riscv_0_axi_periph_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0.dcp d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0.dcp d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0_stub.v d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.v d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Vivado/AudioFilters/AudioFilters.runs/block_design_microblaze_riscv_0_axi_periph_0_synth_1/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.vhdl d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir D:/Vivado/AudioFilters/AudioFilters.ip_user_files/ip/block_design_microblaze_riscv_0_axi_periph_0]} {
  catch { 
    file copy -force d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.v D:/Vivado/AudioFilters/AudioFilters.ip_user_files/ip/block_design_microblaze_riscv_0_axi_periph_0
  }
}

if {[file isdir D:/Vivado/AudioFilters/AudioFilters.ip_user_files/ip/block_design_microblaze_riscv_0_axi_periph_0]} {
  catch { 
    file copy -force d:/Vivado/AudioFilters/AudioFilters.gen/sources_1/bd/block_design/ip/block_design_microblaze_riscv_0_axi_periph_0/block_design_microblaze_riscv_0_axi_periph_0_stub.vhdl D:/Vivado/AudioFilters/AudioFilters.ip_user_files/ip/block_design_microblaze_riscv_0_axi_periph_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "block_design_microblaze_riscv_0_axi_periph_0_synth_1" END { }
